name: dcache
description: cache deletion utility.
version: 1.0.0
homepage: https://github.com/ilshookim/dcache

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  dcli: ^0.34.1
  args: ^1.6.0
  shelf: ^0.7.9
  shelf_router: ^0.7.3

dev_dependencies:
  pedantic: ^1.9.0
